### ISSUE TITLE
how to use it local ? 

### ISSUE THREAD

**Issue by SmallMunich** [lavishsaluja/Ground-Detection#3]
Hi, @lavishsaluja. I want to run it locally. However, I could not know this data format. for example: points inputs format and how to debug it?

**Comment by lavishsaluja** [comment]
Hi, @SmallMunich. Happy to know you're interested in the project.

Right now my parsing function `parse_url` is for a point cloud file (.pcd/.bin) stored in AWS. If you want to run local, you'll have to write a function to convert your point cloud or bin file into numpy array, so the output format is a numpy array which needs to be passed with the function `getGround_World` which will return you two different numpy arrays (one corresponding to ground points `z_filter` and the other corresponding to non-ground points `world` from the point cloud file.

You won't need to debug anything pretty much if you are able to convert your local point cloud file into a numpy array & return it. The numpy array should look something like `[[x,y,z,I], [x,y,z,I], [x,y,z,I], ...]`

You can use the [libraries in python for point cloud](https://pypi.org/project/pcd/) to read your point cloud, traverse on it and start appending all the points into a list and return the list in the form of a numpy array (because they are always faster on operations)

**Comment by SmallMunich** [comment]
@lavishsaluja , Thanks for your reply quickly. best wishes.

**Comment by lavishsaluja** [comment]
@SmallMunich Happy to help :)

Feel free to again open an issue if you face any problem with the parsing function.

**Comment by SmallMunich** [comment]
Hi, @lavishsaluja . I use it to split ground points. However, it's not robust code. because it will be have some bugs at np.cov() & np.svd() functions. problems is matrix element infs.


`def getGround_points(points, threshold):
    '''
    filter ground and non_ground points
    :@param points array
    :@param threshold value (varies between 0.1 to 0.3 generally)
    '''
    xyz = points
    height_col = int(np.argmin(np.var(xyz, axis=0))) # search this min var dimension

    temp = np.zeros((len(xyz[:,1]),4), dtype=float)
    temp[:,:3] = xyz[:,:3]
    temp[:,3] = np.arange(len(xyz[:,1]))
    xyz = temp

    z_filter = xyz[(xyz[:,height_col]<np.mean(xyz[:,height_col]) + 1.5*np.std(xyz[:,height_col])) & (xyz[:,height_col]>np.mean(xyz[:,height_col]) - 1.5*np.std(xyz[:,height_col]))]

    max_z, min_z = np.max(z_filter[:,height_col]), np.min(z_filter[:,height_col])
    z_filter[:,height_col] = (z_filter[:,height_col] - min_z)/(max_z - min_z) # z-height normalize
    iter_cycle = 10
    for i in range(iter_cycle):
        covariance = np.cov(z_filter[:,:3].T)
        w,v,h = np.linalg.svd(np.matrix(covariance))
        normal_vector = w[np.argmin(v)]
        filter_mask = np.asarray(np.abs(np.matrix(normal_vector)*np.matrix(z_filter[:,:3]).T ) < threshold)
        z_filter = np.asarray([z_filter[index[1]] for index, a in np.ndenumerate(filter_mask) if a == True])

    z_filter[:, height_col] = z_filter[:, height_col] * (max_z-min_z) + min_z
    world = np.array([row for row in xyz if row[3] not in z_filter[:,3]])

    return z_filter, world`

can you help me for explain the hard value 1.5 is personal sets?  and how to solve np.cov() & np.svd() receive infs ?  thanks

**Comment by lavishsaluja** [comment]
Hi @SmallMunich Can you please post your error message here and first two elements of your points array from the point cloud?

I'll get back on this to you though tomorrow if possible.

**Comment by SmallMunich** [comment]
Hi, @lavishsaluja . this error message is as follows:

convert.py:93: RuntimeWarning: Degrees of freedom <= 0 for slice
  covariance = np.cov(z_filter[:,:3].T)
/home/holo/anaconda3/lib/python3.7/site-packages/numpy/lib/function_base.py:2455: RuntimeWarning: divide by zero encountered in true_divide
  c *= np.true_divide(1, fact)
/home/holo/anaconda3/lib/python3.7/site-packages/numpy/lib/function_base.py:2455: RuntimeWarning: invalid value encountered in multiply
  c *= np.true_divide(1, fact)
Traceback (most recent call last):
  File "convert_images.py", line 221, in <module>
    load_exported_plys(ply_packages_path)
  File "convert_images.py", line 216, in load_exported_plys
    plysToImages(plys_package_path , imgs_package_path)
  File "convert_images.py", line 204, in plysToImages
    convert(ply_file, img_file)
  File "convert_images.py", line 180, in convert
    img ,meta = OrthProject(raw_point_cloud, 0, 1, world_center=world_center, z_range=[0.2,2] )
  File "convert_images.py", line 153, in OrthProject
    ground_points, non_ground_points = getGround_points(transfer_points, float(0.1))
  File "convert_images.py", line 95, in getGround_points
    w,v,h = np.linalg.svd(np.matrix(covariance))
  File "<__array_function__ internals>", line 6, in svd
  File "/home/holo/anaconda3/lib/python3.7/site-packages/numpy/linalg/linalg.py", line 1636, in svd
    u, s, vh = gufunc(a, signature=signature, extobj=extobj)
  File "/home/holo/anaconda3/lib/python3.7/site-packages/numpy/linalg/linalg.py", line 106, in _raise_linalgerror_svd_nonconvergence
    raise LinAlgError("SVD did not converge")
numpy.linalg.LinAlgError: SVD did not converge


######################################################################
this point cloud ply file download link is : 

web link: https://pan.baidu.com/s/1RRPB_hmybp69tyerWONIag  password: wqww

point cloud datasets is : [ [x, y, z], [x, y, z] ...]  not have intensity

**Comment by lavishsaluja** [comment]
OK, not having intensity in the array won't be a problem if you're not using my parsing function & you've your own custom one.

I'm not sure what this error is (I've not tried to reproduce it though) as my end semester exams are going on, I might check on this again on my machine once the exams end.

I can give you a few resources which might help you know about this, [Check out PCA section in this slide by Professor, Chris](http://www.ctralie.com/Teaching/COMPSCI290/Lectures/10_PCA/slides.pdf) and [ground removal method on this paper by Latte project](https://arxiv.org/abs/1904.09085)

Let me know if you get any leads.
